core/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'

  resources :products

  match '/locale/set' => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state' => 'checkout#update', :as => :update_checkout
  match '/checkout/:state' => 'checkout#edit', :as => :checkout_state
  match '/checkout' => 'checkout#edit', :state => 'address', :as => :checkout

  # non-restful admin checkout stuff
  match '/admin/orders/:order_number/checkout' => 'admin/checkout#update', :method => :post, :as => :admin_orders_checkout
  match '/admin/orders/:order_number/checkout/(:state)' => 'admin/checkout#edit', :method => :get, :as => :admin_orders_checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  match '/cart', :to => 'orders#edit', :via => :get, :as => :cart
  match '/cart', :to => 'orders#update', :via => :put, :as => :update_cart
  match '/cart/empty', :to => 'orders#empty', :via => :put, :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # Search routes
  match 's/*product_group_query' => 'products#index', :as => :simple_search
  match '/pg/:product_group_name' => 'products#index', :as => :pg_search
  match '/t/*id/s/*product_group_query' => 'taxons#show', :as => :taxons_search
  match 't/*id/pg/:product_group_name' => 'taxons#show', :as => :taxons_pg_search

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id' => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #



  namespace :admin do
    resources :zones
    resources :users
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end
    resources :option_types do
      collection do
        post :update_positions
      end
    end
    
    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
        get :user
      end

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end


    resources :trackers
    resources :payment_methods
    resources :mail_methods
  end

  match '/admin' => 'admin/orders#index', :as => :admin

  match '/content/cvv' => 'content#cvv'

  #RAILS3 TODO - we should disable this by default
  #match '/:controller(/:action(/:id(.:format)))'

  # a catchall route for "static" content (except paths with explicit extensions: .html, .ico, etc)
  #if Spree::Config.instance && Spree::Config.get(:use_content_controller)
    match '/*path' => 'content#show'
  #end
end

core/app/controllers/admin/general_settings_controller.rb
class Admin::GeneralSettingsController < Admin::BaseController

  def update
    Spree::Config.set(params[:preferences])

    respond_to do |format|
      format.html {
        redirect_to admin_general_settings_path
      }
    end
  end

  def dismiss_alert
    if request.xhr? and params[:alert_id]
      dismissed = Spree::Config[:dismissed_spree_alerts] || ''
      Spree::Config.set :dismissed_spree_alerts => dismissed.split(',').push(params[:alert_id]).join(',')
      filter_dismissed_alerts
      render :nothing => true
    end
  end

end

core/app/views/admin/general_settings/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t('edit_general_settings') %></h1>

<%= form_tag(admin_general_settings_path, :method => :put) do %>
  <p>
    <label><%= t("site_name") %></label>
    <%= text_field_tag('preferences[site_name]', Spree::Config[:site_name]) %>
  </p>
  <p>
    <label><%= t("default_seo_title") %></label>
    <%= text_field_tag('preferences[default_seo_title]', Spree::Config[:default_seo_title]) %>
  </p>
  <p>
    <label><%= t('site_url') %></label>
    <%= text_field_tag('preferences[site_url]', Spree::Config[:site_url])%>
  </p>
  <p>
    <label>
      <input name="preferences[allow_ssl_in_production]" type="hidden" value="0" />
      <%= check_box_tag('preferences[allow_ssl_in_production]', "1", Spree::Config[:allow_ssl_in_production]) %>
      <%= t('allow_ssl_to_be_used_when_in_production_mode') %>
    </label>
  </p>

  <p>
    <label>
      <input name="preferences[allow_ssl_in_development_and_test]" type="hidden" value="0" />
      <%= check_box_tag('preferences[allow_ssl_in_development_and_test]', "1", Spree::Config[:allow_ssl_in_development_and_test]) %>
      <%= t('allow_ssl_to_be_used_when_in_developement_and_test_modes') %>
    </label>
  </p>

  <p>
    <label>
      <input name="preferences[check_for_spree_alerts]" type="hidden" value="0" />
      <%= check_box_tag('preferences[check_for_spree_alerts]', "1", Spree::Config[:check_for_spree_alerts]) %>
      <%= t('spree_alert_checking') %>
    </label>
 </p>

  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_general_settings_url %>
  </p>
<% end %>

core/app/views/admin/general_settings/show.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("general_settings") %></h1>

<table>
  <tr>
    <th scope="row"><%= t("site_name") %>:</th>
    <td><%=  Spree::Config[:site_name] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("default_seo_title") %>:</th>
    <td><%=  Spree::Config[:default_seo_title] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("site_url") %>:</th>
    <td><%=  Spree::Config[:site_url] %></td>
  </tr>
  <tr>
	<td colspan="2">
	  <%= (Spree::Config[:allow_ssl_in_production] ? t("ssl_will_be_used_in_production_mode") : t("ssl_will_not_be_used_in_production_mode")) %>
	</td>
  </tr>
  <tr>
	<td colspan="2">
	  <%= (Spree::Config[:allow_ssl_in_development_and_test] ? t("ssl_will_be_used_in_development_and_test_modes") : t("ssl_will_not_be_used_in_development_and_test_modes")) %>
  </td>
  </tr>
  <tr>
  <td colspan="2">
    <%= (Spree::Config[:check_for_spree_alerts] ? t("spree_alert_checking") : t("spree_alert_not_checking")) %>
  </tr>
</table>

<p><%= link_to_with_icon 'edit', t("edit"), edit_admin_general_settings_path, :id => 'admin_general_settings_link' %></p>