core/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'

  resources :products

  match '/locale/set' => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state' => 'checkout#update', :as => :update_checkout
  match '/checkout/:state' => 'checkout#edit', :as => :checkout_state
  match '/checkout' => 'checkout#edit', :state => 'address', :as => :checkout

  # non-restful admin checkout stuff
  match '/admin/orders/:order_number/checkout' => 'admin/checkout#update', :method => :post, :as => :admin_orders_checkout
  match '/admin/orders/:order_number/checkout/(:state)' => 'admin/checkout#edit', :method => :get, :as => :admin_orders_checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  match '/cart', :to => 'orders#edit', :via => :get, :as => :cart
  match '/cart', :to => 'orders#update', :via => :put, :as => :update_cart
  match '/cart/empty', :to => 'orders#empty', :via => :put, :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # Search routes
  match 's/*product_group_query' => 'products#index', :as => :simple_search
  match '/pg/:product_group_name' => 'products#index', :as => :pg_search
  match '/t/*id/s/*product_group_query' => 'taxons#show', :as => :taxons_search
  match 't/*id/pg/:product_group_name' => 'taxons#show', :as => :taxons_pg_search

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id' => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #



  namespace :admin do
    resources :zones
    resources :users
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end
    resources :option_types do
      collection do
        post :update_positions
      end
    end
    
    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
        get :user
      end

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end


    resources :trackers
    resources :payment_methods
    resources :mail_methods
  end

  match '/admin' => 'admin/orders#index', :as => :admin

  match '/content/cvv' => 'content#cvv'

  #RAILS3 TODO - we should disable this by default
  #match '/:controller(/:action(/:id(.:format)))'

  # a catchall route for "static" content (except paths with explicit extensions: .html, .ico, etc)
  #if Spree::Config.instance && Spree::Config.get(:use_content_controller)
    match '/*path' => 'content#show'
  #end
end

core/app/models/product_property.rb
class ProductProperty < ActiveRecord::Base
  belongs_to :product
  belongs_to :property

  validates :property, :presence => true

  # virtual attributes for use with AJAX completion stuff
  def property_name
    property.name if property
  end

  def property_name=(name)
    self.property = Property.find_by_name(name) unless name.blank?
  end
end

core/app/controllers/admin/product_properties_controller.rb
class Admin::ProductPropertiesController < Admin::ResourceController
  belongs_to :product, :find_by => :permalink
  before_filter :find_properties

  private

  def find_properties
    @properties = Property.all.map(&:name)
  end
end

core/app/helpers/admin/product_properties_helper.rb
module Admin::ProductPropertiesHelper

  # Generates the appropriate field name for attribute_fu.  Normally attribute_fu handles this but we've got a
  # special case where we need text_field_with_autocomplete and we have to recreate attribute_fu's naming
  # scheme manually.
  def property_fu_name(product_property, number)
    if product_property.new_record?
      "product[product_property_attributes][new][#{number}][property_name]"
    else
      "product[product_property_attributes][#{product_property.id}][property_name]"
    end
  end

  def property_fu_value(product_property, number)
    if product_property.new_record?
      "product[product_property_attributes][new][#{number}][value]"
    else
      "product[product_property_attributes][#{product_property.id}][value]"
    end
  end
end

core/app/views/admin/product_properties/_product_property_fields.html.erb
<tr class="product_property fields">
  <td class='property_name'>
    <%= f.text_field :property_name, :class => "autocomplete" %>
  </td>
  <td class='value'>
    <%= f.text_field :value, :class => "autocomplete" %>
  </td>
  <td class="actions">
    <%= link_to_remove_fields t("remove"), f %>
  </td>
</tr>

core/app/views/admin/product_properties/index.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Product Properties"} %>

<%= render "shared/error_messages", :target => @product %>

<%= form_for(@product, :url => admin_product_url(@product), :html => { :method => :put }) do |f| %>
  <table class="index">
    <thead>
      <tr>
        <th><%= t("property") %></th>
        <th><%= t("value") %></th>
        <th><%= t("action") %></th>
      </tr>
    </thead>
    <tbody id="product_properties">
      <%= f.fields_for :product_properties do |pp_form| %>
        <%= render 'product_property_fields', :f => pp_form %>
      <% end %>
    </tbody>
  </table>

  <input type="hidden" name="clear_product_properties" value="true">

  <p class='add_product_properties'>
    <%= link_to_add_fields  icon('add') + ' ' + t("add_product_properties"),
                            "tbody#product_properties",
                            f,
                            :product_properties %>

    &nbsp;&nbsp;

  	<span id="new_ptype_link">
  	  <%= link_to t("select_from_prototype"), available_admin_prototypes_url,
  	              :remote => true, 'data-update' => "prototypes" %>
  	</span>
	</p>
	<div id="prototypes"></div>
	<%= image_tag "spinner.gif", :plugin=>"spree", :style => "display:none", :id => 'busy_indicator' %>
	<br/>
  <%= render :partial => 'admin/shared/edit_resource_links' %>
<% end %>

<%= javascript_tag do %>
  var properties = [<%= @properties.map{|id| "'#{id}'"}.join(', ') %>];

  $("#product_properties input.autocomplete").live("keydown", function(){
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete(properties);
      $(this).focus();
    }
  });
<% end %>