core/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'

  resources :products

  match '/locale/set' => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state' => 'checkout#update', :as => :update_checkout
  match '/checkout/:state' => 'checkout#edit', :as => :checkout_state
  match '/checkout' => 'checkout#edit', :state => 'address', :as => :checkout

  # non-restful admin checkout stuff
  match '/admin/orders/:order_number/checkout' => 'admin/checkout#update', :method => :post, :as => :admin_orders_checkout
  match '/admin/orders/:order_number/checkout/(:state)' => 'admin/checkout#edit', :method => :get, :as => :admin_orders_checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  match '/cart', :to => 'orders#edit', :via => :get, :as => :cart
  match '/cart', :to => 'orders#update', :via => :put, :as => :update_cart
  match '/cart/empty', :to => 'orders#empty', :via => :put, :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # Search routes
  match 's/*product_group_query' => 'products#index', :as => :simple_search
  match '/pg/:product_group_name' => 'products#index', :as => :pg_search
  match '/t/*id/s/*product_group_query' => 'taxons#show', :as => :taxons_search
  match 't/*id/pg/:product_group_name' => 'taxons#show', :as => :taxons_pg_search

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id' => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #



  namespace :admin do
    resources :zones
    resources :users
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end
    resources :option_types do
      collection do
        post :update_positions
      end
    end
    
    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
        get :user
      end

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end


    resources :trackers
    resources :payment_methods
    resources :mail_methods
  end

  match '/admin' => 'admin/orders#index', :as => :admin

  match '/content/cvv' => 'content#cvv'

  #RAILS3 TODO - we should disable this by default
  #match '/:controller(/:action(/:id(.:format)))'

  # a catchall route for "static" content (except paths with explicit extensions: .html, .ico, etc)
  #if Spree::Config.instance && Spree::Config.get(:use_content_controller)
    match '/*path' => 'content#show'
  #end
end

core/app/models/product_group.rb
# *ProductGroups* are used for creating and managing sets of products.
# Product group can be either anonymous(adhoc) or named.
#
# Anonymous Product groups are created by combining product scopes generated from url
# in 2 formats:
#
#   /t/*taxons/s/name_of_scope/comma_separated_arguments/name_of_scope_that_doesn_take_any//order
#   */s/name_of_scope/comma_separated_arguments/name_of_scope_that_doesn_take_any//order
#
# Named product groups can be created from anonymous ones, lub from another named scope
# (using ProductGroup.from_url method).
# Named product groups have pernament urls, that don't change even after changes
# to scopes are made, and come in two types.
#
#   /t/*taxons/pg/named_product_group
#   */pg/named_product_group
#
# first one is used for combining named scope with taxons, named product group can
# have #in_taxon or #taxons_name_eq scope defined, result should combine both
# and return products that exist in both taxons.
#
# ProductGroup#dynamic_products returns chain of named scopes generated from order and
# product scopes. So you can do counting, calculations etc, on resulted set of products,
# without retriving all records.
#
# ProductGroup operates on named scopes defined for product in Scopes::Product,
# or generated automatically by meta_search
#
class ProductGroup < ActiveRecord::Base
  validates :name, :presence => true # TODO ensure that this field is defined as not_null
  validates_associated :product_scopes

  before_save :set_permalink
  after_save :update_memberships

  has_and_belongs_to_many :cached_products, :class_name => "Product"
  # name
  has_many :product_scopes
  accepts_nested_attributes_for :product_scopes

  # Testing utility: creates new *ProductGroup* from search permalink url.
  # Follows conventions for accessing PGs from URLs, as decoded in routes
  def self.from_url(url)
    pg = nil;
    case url
    when /\/t\/(.+?)\/s\/(.+)/  then taxons = $1; attrs = $2;
    when /\/t\/(.+?)\/pg\/(.+)/ then taxons = $1; pg_name = $2;
    when /(.*?)\/s\/(.+)/       then attrs = $2;
    when /(.*?)\/pg\/(.+)/      then pg_name = $2;
    else                        return(nil)
    end

    if pg_name && opg = ProductGroup.find_by_permalink(pg_name)
      pg = new.from_product_group(opg)
    elsif attrs
      attrs = url.split("/")
      pg = new.from_route(attrs)
    end
    taxon = taxons && taxons.split("/").last
    pg.add_scope("in_taxon", taxon) if taxon

    pg
  end

  def from_product_group(opg)
    self.product_scopes = opg.product_scopes.map{|ps|
      ps = ps.clone;
      ps.product_group_id = nil;
      ps.product_group = self;
      ps
    }
    self
  end

  def from_route(attrs)
    self.order_scope = attrs.pop if attrs.length % 2 == 1
    attrs.each_slice(2) do |scope|
      next unless Product.respond_to?(scope.first)
      add_scope(scope.first, scope.last.split(","))
    end
    self
  end

  def from_search(search_hash)
    search_hash.each_pair do |scope_name, scope_attribute|
      add_scope(scope_name, scope_attribute)
    end

    self
  end

  def add_scope(scope_name, arguments=[])
    if scope_name.to_s !~ /eval|send|system|[^a-z0-9_!?]/
      self.product_scopes << ProductScope.new({
          :name => scope_name.to_s,
          :arguments => [*arguments]
        })
    else
      raise ArgumentError.new("'#{scope_name}` can't be used as scope")
    end
    self
  end

  def apply_on(scopish, use_order = true)
    # There's bug in AR, it doesn't merge :order, instead it takes order
    # from first nested_scope so we have to apply ordering FIRST.
    # see #2253 on rails LH
    base_product_scope = scopish
    if use_order && !self.order_scope.blank? && Product.respond_to?(self.order_scope.intern)
      base_product_scope = base_product_scope.send(self.order_scope)
    end

    return self.product_scopes.reject {|s| s.is_ordering? }.inject(base_product_scope) do |result, scope|
      scope.apply_on(result)
    end

  end

  # returns chain of named scopes generated from order scope and product scopes.
  def dynamic_products(use_order = true)
    apply_on(Product.group_by_products_id, use_order)
  end

  # Does the final ordering if requested
  # TODO: move the order stuff out of the above - is superfluous now
  def products(use_order = true)
    cached_group = Product.in_cached_group(self)
    if cached_group.limit(1).blank?
      dynamic_products(use_order)
    elsif !use_order
      cached_group
    else
      product_scopes.select {|s|
        s.is_ordering?
      }.inject(cached_group) {|res,order|
        order.apply_on(res)
      }
    end
  end

  def include?(product)
    res = apply_on(Product.id_equals(product.id), false)
    res.count > 0
  end

  def scopes_to_hash
    result = {}
    self.product_scopes.each do |scope|
      result[scope.name] = scope.arguments
    end
    result
  end

  # generates ProductGroup url
  def to_url
    if (new_record? || name.blank?)
      result = ""
      result+= self.product_scopes.map{|ps|
        [ps.name, ps.arguments.join(",")]
      }.flatten.join('/')
      result+= self.order_scope if self.order_scope

      result
    else
      name.to_url
    end
  end

  def set_permalink
    self.permalink = self.name.to_url
  end

  def update_memberships
    # wipe everything directly to avoid expensive in-rails sorting
    ActiveRecord::Base.connection.execute "DELETE FROM product_groups_products WHERE product_group_id = #{self.id}"

    # and generate the new group entirely in SQL
    ActiveRecord::Base.connection.execute "INSERT INTO product_groups_products #{dynamic_products(false).scoped(:select => "products.id, #{self.id}").to_sql}"
  end

  def generate_preview(size = Spree::Config[:admin_pgroup_preview_size])
    count = self.class.count_by_sql ["SELECT COUNT(*) FROM product_groups_products WHERE product_groups_products.product_group_id = ?", self]

    return count, products.limit(size)
  end

  def to_s
    "<ProductGroup" + (id && "[#{id}]").to_s + ":'#{to_url}'>"
  end
  
  def to_param
    self.permalink
  end

  def order_scope
    if scope = product_scopes.detect {|s| s.is_ordering?}
      scope.name
    end
  end

  def order_scope=(scope_name)
    if scope = product_scopes.detect {|s| s.is_ordering?}
      scope.update_attribute(:name, scope_name)
    else
      self.product_scopes.build(:name => scope_name, :arguments => [])
    end
  end

  # Build a new product group with a scope to filter by specified products
  def self.new_from_products(products, attrs = {})
    pg = new(attrs)
    pg.product_scopes.build(:name => 'with_ids', :arguments => [products.map(&:id).join(',')])
    pg
  end

end

core/app/controllers/admin/product_groups_controller.rb
class Admin::ProductGroupsController < Admin::ResourceController
  before_filter :patch_params, :only => [:update]
  
  def preview
    @product_group = ProductGroup.new(params[:product_group])
    @product_group.name = "for_preview"
    respond_with(@product_group) { |format| format.html { render :partial => 'preview', :layout => false } }
  end

  protected

    def find_resource
      ProductGroup.find_by_permalink(params[:id])
    end
     
    def location_after_save
      edit_admin_product_group_path(@product_group)
    end

    def collection
      params[:search] ||= {}
      params[:search][:meta_sort] ||= "name.asc"
      @search = super.metasearch(params[:search])
      @collection = @search.paginate( :per_page => Spree::Config[:per_page],
                                      :page     => params[:page])
    end
    
  private

    # Consolidate argument arrays for nested product_scope attributes
    # Necessary for product scopes with multiple arguments
    def patch_params
      if params["product_group"] and params["product_group"]["product_scopes_attributes"].is_a?(Array)
        params["product_group"]["product_scopes_attributes"] = params["product_group"]["product_scopes_attributes"].group_by {|a| a["id"]}.map do |scope_id, attrs|
          a = { "id" => scope_id, "arguments" => attrs.map{|a| a["arguments"] }.flatten }
          if name = attrs.first["name"]
            a["name"] = name
          end
          a
        end
      end
    end



end

core/app/helpers/admin/product_groups_helper.rb
module Admin::ProductGroupsHelper

  # Allow certain scope attributes to have a custom field type
  def product_scope_field(product_scope, i)
    value = (product_scope.arguments || [])[i]
    name = "product_group[product_scopes_attributes][][arguments][]"
    helper_method_for_scope = Scopes::Product::ATTRIBUTE_HELPER_METHODS[product_scope.name.to_sym] || :text_field_tag
    send(helper_method_for_scope, name, value)
  end

end

core/app/views/admin/product_groups/_preview.html.erb
<% count, preview = @product_group.generate_preview(Spree::Config[:admin_pgroup_preview_size]) %>

<h2><%= ProductGroup.human_attribute_name(:products) %> (<%= count %>)</h2>

<% if count == 0 %>
  <p><%= t('no_match_found') %></p>
<% else %>

  <% if count > Spree::Config[:admin_pgroup_preview_size] %>
    <p><%= t('showing_first_n', :n => Spree::Config[:admin_pgroup_preview_size]) %></p>
  <% end %>

  <table class="index">
    <thead>
    <tr>
      <th><%= Product.human_attribute_name(:name) %></th>
      <th><%= t(:action) %></th>
    </tr>
    </thead>
    <tbody>
    <% preview.each do |product| %>
      <tr>
        <td>
          <%= link_to product.name, product_url(product) %>
        </td>
        <td>
          <%= link_to t(:edit), edit_admin_product_path(product) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

core/app/views/admin/product_groups/_product_scope.html.erb
<tr id="<%= dom_id product_scope %>">
  <td>
    <label><%= t(:name, :scope => [:product_scopes, :scopes, product_scope.name]) %></label>
    <% if description = t(:description, :scope => [:product_scopes, :scopes, product_scope.name], :default => "") and description.present? %>
      <br /><%= description %>
    <% end %>
  </td>
  <td>
    <% if arguments = Scopes::Product.arguments_for_scope_name(product_scope.name.strip) %>
      <table><tr>
      <% arguments.each_with_index do |argument, i| %>
        <td>
          <label><%= t(argument, :scope => [:product_scopes, :scopes, product_scope.name, :args]) %></label><br />
          <%= hidden_field_tag "product_group[product_scopes_attributes][][id]", product_scope.id %>
          <%= product_scope_field product_scope, i %>
        </td>
      <% end %>
      </tr></table>
    <% end %>
  </td>
  <td class="actions">
    <%= link_to_with_icon 'cross', '', admin_product_group_product_scope_path(@product_group, product_scope), 'data-remote' => true, 'data-method' => 'delete' %>
  </td>
</tr>

core/app/views/admin/product_groups/edit.html.erb
<%= render 'admin/shared/product_sub_menu' %>

<h1><%= t('editing_product_group') %></h1>

<fieldset id="product_group_forms_container">

  <%= form_for(@product_group, :url => object_url, :html => { :id => 'product-group-form', :method => :put, 'data-remote' => true }) do |f| %>

      <%= f.field_container :name do %>
        <%= f.label :name, t("name") %><br />
        <%= f.text_field :name %>
        <%= f.error_message_on :name %>
      <% end %>

      <%= f.field_container :order_scope do %>
        <%= f.label :order_scope, t("sort_ordering") %><br />
        <%= f.select(:order_scope, Scopes::Product::ORDERING.collect{|p| [ t(:name, :scope =>[:product_scopes, :scopes, p]), p.to_s ] }) %>
      <% end %>

      <table id="product_scopes">
        <%= render :partial => 'product_scope', :collection => @product_group.product_scopes.reject {|s| s.is_ordering? } %>
      </table>

    <%=  button t("update") %>

  <% end %>


  <%= form_tag(admin_product_group_product_scopes_path(@product_group), 'data-remote' => true, :id => 'new_product_group_form') do %>
    <%
    options =
    grouped_options_for_select(
    Scopes::Product::SCOPES.map do |group_name, scopes|
      [
        t(:name, :scope => [:product_scopes, :groups, group_name]),
        scopes.keys.map do |scope_name|
          [ t(:name, :scope => [:product_scopes, :scopes, scope_name]), scope_name]
        end
      ]
    end
    )
    %>
    <p>
      <label for="product_scope_name"><%= t('add_scope') %></label>
      <%= select_tag("product_scope[name]", options) %>
      <input type="submit" value="<%= t('add') %>" />
    </p>
  <% end %>


</fieldset>


<fieldset id="preview_container">
  <%= render 'preview' %>
</fieldset>

core/app/views/admin/product_groups/index.html.erb
<% render 'admin/shared/product_sub_menu' %>
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_product_group"), new_object_url, :icon => 'add', :id => 'new_product_group_link' %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("listing_product_groups") %></h1>

<table class="index" id='listing_product_groups'>
  <thead>
    <tr>
      <th><%= ProductGroup.human_attribute_name("name") %></th>
      <th><%= ProductGroup.human_attribute_name("url") %></th>
      <th><%= ProductGroup.human_attribute_name("product_scopes")  %></th>
      <th><%= ProductGroup.human_attribute_name("product_count")  %></th>
      <th><%= t(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <% @product_groups.each do |pg| %>
      <tr id="<%= dom_id pg %>">
        <td><%= link_to pg.name, [:admin, pg] %></td>
        <td><%= link_to pg_search_path(:product_group_name => pg.permalink), pg_search_path(:product_group_name => pg.permalink) %></td>
        <td><%== pg.product_scopes.map(&:to_sentence).join("<br />") %></td>
        <td><%= pg.products.count %></td>
        <td>
          <%= link_to_edit pg, :class => 'admin_edit_product_group' %> &nbsp; <%= link_to_delete pg %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate(:previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>

core/app/views/admin/product_groups/new.html.erb
<%= render 'admin/shared/product_sub_menu' %>
<%= form_for(:product_group,  :url => collection_url, :html => { :id => 'product-group-form', :multipart => true }) do |f| %>
  <fieldset>
    <legend><%= t(:product_group) %></legend>
    <%= f.field_container :name do %>
      <%= f.label :name, t("name") %>
      <%= f.text_field :name %>
      <%= f.error_message_on :name %>
    <% end %>
  </fieldset>
  <%=  button t("create") %>
<% end %>

core/app/views/admin/product_groups/show.html.erb
<% render 'admin/shared/product_sub_menu' %>
<h2><%= ProductGroup.model_name.human %></h2>
<p>
  <%= ProductGroup.human_attribute_name(:name) %>: <%= @product_group.name %>
</p>
<p>
  <%= ProductGroup.human_attribute_name(:url) %>: <%= link_to @product_group.permalink, "/pg/#{@product_group.permalink}" %>
</p>

<h2><%= ProductGroup.human_attribute_name(:product_scopes) %>(<%= @product_group.product_scopes.count %>)</h2>
<table class="product-scopes">
  <thead>
    <tr>
      <th><%= ProductScope.human_attribute_name(:description) %></th>
      <th><%= ProductScope.human_attribute_name(:arguments) %></th>
    </tr>
  </thead>
  <tbody>
    <% @product_group.product_scopes.each do |product_scope| %>
      <tr <%= !product_scope.valid? ? "class='invalid'":'' %>>
        <td>
          <%= product_scope.to_sentence %>
        </td>
        <td>
          <%= product_scope.arguments.join(", ") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render :partial => 'preview.html' %>

core/app/views/admin/product_groups/update.js.erb
jQuery('#preview_container').html('<%= escape_javascript( render('admin/product_groups/preview') ) %>');
<% notice = flash.delete(:notice) %>
flash_notice = jQuery('.flash.notice');
if (flash_notice.length > 0) {
  flash_notice.html('<%= notice %>');
} else {
  jQuery('#content h1').before('<div class="flash notice"><%= notice %></div>');
}