core/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'

  resources :products

  match '/locale/set' => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state' => 'checkout#update', :as => :update_checkout
  match '/checkout/:state' => 'checkout#edit', :as => :checkout_state
  match '/checkout' => 'checkout#edit', :state => 'address', :as => :checkout

  # non-restful admin checkout stuff
  match '/admin/orders/:order_number/checkout' => 'admin/checkout#update', :method => :post, :as => :admin_orders_checkout
  match '/admin/orders/:order_number/checkout/(:state)' => 'admin/checkout#edit', :method => :get, :as => :admin_orders_checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  match '/cart', :to => 'orders#edit', :via => :get, :as => :cart
  match '/cart', :to => 'orders#update', :via => :put, :as => :update_cart
  match '/cart/empty', :to => 'orders#empty', :via => :put, :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # Search routes
  match 's/*product_group_query' => 'products#index', :as => :simple_search
  match '/pg/:product_group_name' => 'products#index', :as => :pg_search
  match '/t/*id/s/*product_group_query' => 'taxons#show', :as => :taxons_search
  match 't/*id/pg/:product_group_name' => 'taxons#show', :as => :taxons_pg_search

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id' => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #



  namespace :admin do
    resources :zones
    resources :users
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end
    resources :option_types do
      collection do
        post :update_positions
      end
    end
    
    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
        get :user
      end

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end


    resources :trackers
    resources :payment_methods
    resources :mail_methods
  end

  match '/admin' => 'admin/orders#index', :as => :admin

  match '/content/cvv' => 'content#cvv'

  #RAILS3 TODO - we should disable this by default
  #match '/:controller(/:action(/:id(.:format)))'

  # a catchall route for "static" content (except paths with explicit extensions: .html, .ico, etc)
  #if Spree::Config.instance && Spree::Config.get(:use_content_controller)
    match '/*path' => 'content#show'
  #end
end

core/app/models/taxon.rb
class Taxon < ActiveRecord::Base
  acts_as_nested_set :dependent => :destroy

  belongs_to :taxonomy
  has_and_belongs_to_many :products
  before_create :set_permalink

  validates :name, :presence => true
  # has_attached_file :icon,
  #               :styles => { :mini => '32x32>', :normal => '128x128>' },
  #              :default_style => :mini,
  #               :url => "/assets/taxons/:id/:style/:basename.:extension",
  #               :path => ":rails_root/public/assets/taxons/:id/:style/:basename.:extension",
  #               :default_url => "/images/default_taxon.png"


  include ::ProductFilters  # for detailed defs of filters

  # indicate which filters should be used for a taxon
  # this method should be customized to your own site
  def applicable_filters
    fs = []
    # fs << ProductFilters.taxons_below(self)
    ## unless it's a root taxon? left open for demo purposes

    fs << ProductFilters.price_filter if ProductFilters.respond_to?(:price_filter)
    fs << ProductFilters.brand_filter if ProductFilters.respond_to?(:brand_filter)
    fs
  end

  # Creates permalink based on .to_url method provided by stringx gem
  def set_permalink
    if parent_id.nil?
      self.permalink = name.to_url if self.permalink.blank?
    else
      parent_taxon = Taxon.find(parent_id)
      self.permalink = [parent_taxon.permalink, (self.permalink.blank? ? name.to_url : self.permalink.split("/").last)].join('/')
    end
  end

  def active_products
    scope = self.products.active
    scope = scope.on_hand unless Spree::Config[:show_zero_stock_products]
    scope
  end

  private
  # obsolete, kept for backwards compat
  def escape(str)
    str.blank? ? "" : str.to_url
  end
end

core/app/controllers/admin/taxons_controller.rb
class Admin::TaxonsController < Admin::BaseController
  include Railslove::Plugins::FindByParam::SingletonMethods

  respond_to :html, :json, :js

  def create
    @taxonomy = Taxonomy.find(params[:taxonomy_id])
    @taxon = @taxonomy.taxons.build(params[:taxon])
    if @taxon.save
      respond_with(@taxon) do |format|
        format.json {render :json => @taxon.to_json }
      end
    else
      flash[:error] = I18n.t('errors.messages.could_not_create_taxon')
      respond_with(@taxon) do |format|
        format.html { redirect_to @taxonomy ? edit_admin_taxonomy_url(@taxonomy) : admin_taxonomies_url }
      end
    end
  end

  def update
    update_before
    update_after
    respond_with(@taxon) do |format|
      format.html { redirect_to edit_admin_taxonomy_url(@taxonomy) }
      format.json { render :json => @taxon.to_json }
    end
  end

  def edit
    @taxonomy = Taxonomy.find(params[:taxonomy_id])
    @taxon = @taxonomy.taxons.find(params[:id])
    @permalink_part = @taxon.permalink.split("/").last

    respond_with(:admin, @taxon) 
  end

  def update
    @taxonomy = Taxonomy.find(params[:taxonomy_id])
    @taxon = @taxonomy.taxons.find(params[:id])
    parent_id = params[:taxon][:parent_id]
    new_position = params[:taxon][:position]

    if parent_id || new_position #taxon is being moved
      new_parent = parent_id.nil? ? @taxon.parent : Taxon.find(parent_id.to_i)
      new_position = new_position.nil? ? -1 : new_position.to_i

      # Bellow is a very complicated way of finding where in nested set we
      # should actually move the taxon to achieve sane results,
      # JS is giving us the desired position, which was awesome for previous setup,
      # but now it's quite complicated to find where we should put it as we have
      # to differenciate between moving to the same branch, up down and into
      # first position.
      new_siblings = new_parent.children
      if new_position <= 0 && new_siblings.empty?
        @taxon.move_to_child_of(new_parent)
      elsif new_parent.id != @taxon.parent_id
        if new_position == 0
          @taxon.move_to_left_of(new_siblings.first)
        else
          @taxon.move_to_right_of(new_siblings[new_position-1])
        end
      elsif new_position < new_siblings.index(@taxon)
        @taxon.move_to_left_of(new_siblings[new_position]) # we move up
      else
        @taxon.move_to_right_of(new_siblings[new_position]) # we move down
      end
      # Reset legacy position, if any extensions still rely on it
      new_parent.children.reload.each{|t| t.update_attribute(:position, t.position)}
      
      if parent_id
        @taxon.reload
        @taxon.set_permalink
        @taxon.save!
        @update_children = true
      end
    end

    if params.key? "permalink_part"
      parent_permalink = @taxon.permalink.split("/")[0...-1].join("/")
      parent_permalink += "/" unless parent_permalink.blank?
      params[:taxon][:permalink] = parent_permalink + params[:permalink_part]
    end
    #check if we need to rename child taxons if parent name or permalink changes
    @update_children = true if params[:taxon][:name] != @taxon.name || params[:taxon][:permalink] != @taxon.permalink

    if @taxon.update_attributes(params[:taxon])
      flash[:notice] = flash_message_for(@taxon, :successfully_updated)
    end

    #rename child taxons
    if @update_children
      @taxon.descendants.each do |taxon|
        taxon.reload
        taxon.set_permalink
        taxon.save!
      end
    end
    
    respond_with(@taxon) do |format|
      format.html {redirect_to edit_admin_taxonomy_url(@taxonomy) }
      format.json {render :json => @taxon.to_json }
    end
  end

  def destroy
    @taxon = Taxon.find(params[:id])
    @taxon.destroy
    respond_with(@taxon) { |format| format.json { render :json => '' } }
  end

  def selected
    @product = load_product
    @taxons = @product.taxons

    respond_with(:admin, @taxons)
  end

  def available
    @product = load_product
    @taxons = params[:q].blank? ? [] : Taxon.where('lower(name) LIKE ?', "%#{params[:q].mb_chars.downcase}%")
    @taxons.delete_if { |taxon| @product.taxons.include?(taxon) }

    respond_with(:admin, @taxons)
  end

  def remove
    @product = load_product
    @taxon = Taxon.find(params[:id])
    @product.taxons.delete(@taxon)
    @product.save
    @taxons = @product.taxons

    respond_with(@taxon) { |format| format.js { render_js_for_destroy } }
  end

  def select
    @product = load_product
    @taxon = Taxon.find(params[:id])
    @product.taxons << @taxon
    @product.save
    @taxons = @product.taxons

    respond_with(:admin, @taxons)
  end

  def batch_select
    @product = load_product
    @taxons = params[:taxon_ids].map{|id| Taxon.find(id)}.compact
    @product.taxons = @taxons
    @product.save
    redirect_to selected_admin_product_taxons_url(@product)
  end

  private

  def load_product
    Product.find_by_permalink! params[:product_id]
  end

end

core/app/controllers/taxons_controller.rb
class TaxonsController < Spree::BaseController
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
  helper :products

  respond_to :html

  def show
    @taxon = Taxon.find_by_permalink!(params[:id])
    return unless @taxon

    @searcher = Spree::Config.searcher_class.new(params.merge(:taxon => @taxon.id))
    @products = @searcher.retrieve_products

    respond_with(@taxon)
  end

  private

  def accurate_title
    @taxon ? @taxon.name : super
  end
end

core/app/helpers/admin/taxons_helper.rb
module Admin::TaxonsHelper
  def taxon_path(taxon)
    taxon.ancestors.reverse.collect { |ancestor| ancestor.name }.join( " >> ")
  end
  
  def taxons_checkbox_tree(root, product)
    return '' if root.children.blank?
    content_tag 'ul' do
      root.children.map do |taxon|
        content_tag 'li' do
          [check_box_tag("taxon_ids[]", taxon.id, product.taxons.include?(taxon), :id => "taxon_ids_#{taxon.id}"),
           label_tag("taxon_ids_#{taxon.id}", taxon.name)].join('&nbsp;').html_safe +
          taxons_checkbox_tree(taxon, product)
        end.html_safe
      end.join("\n").html_safe
    end
  end
end

core/app/helpers/taxons_helper.rb
module TaxonsHelper
  def breadcrumbs(taxon, separator="&nbsp;&raquo;&nbsp;")
    return "" if current_page?("/")
    separator = raw(separator)
    crumbs = [content_tag(:li, link_to(t(:home) , root_path) + separator)]
    if taxon
      crumbs << content_tag(:li, link_to(t('products') , products_path) + separator)
      crumbs << taxon.ancestors.collect { |ancestor| content_tag(:li, link_to(ancestor.name , seo_url(ancestor)) + separator) } unless taxon.ancestors.empty?
      crumbs << content_tag(:li, content_tag(:span, taxon.name))
    else
      crumbs << content_tag(:li, content_tag(:span, t('products')))
    end
    crumb_list = content_tag(:ul, raw(crumbs.flatten.map{|li| li.mb_chars}.join))
    content_tag(:div, crumb_list + tag(:br, {:class => 'clear'}, false, true), :class => 'breadcrumbs')
  end


  # Retrieves the collection of products to display when "previewing" a taxon.  This is abstracted into a helper so
  # that we can use configurations as well as make it easier for end users to override this determination.  One idea is
  # to show the most popular products for a particular taxon (that is an exercise left to the developer.)
  def taxon_preview(taxon, max=4)
    products = taxon.active_products.limit(max)
    if (products.size < max) && Spree::Config[:show_descendents]
      taxon.descendants.each do |taxon|
        to_get = max - products.length
        products += taxon.active_products.limit(to_get)
        break if products.size >= max
      end
    end
    products
  end
end

core/app/views/admin/taxons/_form.html.erb
<%= hook :admin_inside_taxon_form, {:f => f} do %>
  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= error_message_on :taxon, :name, :class => 'fullwidth title'  %>
    <%= text_field :taxon, :name  %>
  <% end %>

  <%= f.field_container :permalink_part do %>
    <%= f.label :permalink_part, t("permalink") %><span class="required">*</span><br />
    <%= @taxon.permalink.split("/")[0...-1].join("/") + "/" %><%= text_field_tag :permalink_part, @permalink_part  %>
  <% end %>

  <%= f.field_container :icon do %>
    <%= f.label :icon, t('icon') %><br />
    <%= f.file_field :icon %>
  <% end %>

  <%= f.field_container :description do %>
    <%= f.label :description, t(:description) %><br />
    <%= f.text_area :description %>
  <% end %>

<% end %>

core/app/views/admin/taxons/_taxon_table.html.erb
<table class="index">
  <thead>
  	<tr>
  		<th><%= t("name") %></th>
  		<th><%= t("path") %></th>
  		<th></th>
  	</tr>
  </thead>
  <tbody>
    <% taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon)%>">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
  	    <td class="actions">	                         
		      <%= link_to_delete taxon, :url => remove_admin_product_taxon_url(@product, taxon), :name => icon("delete") + ' ' + t("remove") %>
  	    </td>        
      </tr>
    <% end %>
    <% if taxons.empty? %>
     <tr><td colspan="3"><%= t('none') %>.</td></tr>
    <% end %>
  </tbody>
</table>

core/app/views/admin/taxons/available.js.erb
<script type="text/javascript">
  function displayRow(){
    var row = document.getElementById("captionRow");
    if (row.style.display == '') row.style.display = 'none';
    else row.style.display = '';
  }
</script>
<h4><%= t('available_taxons') %></h4>
<table class="index">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%= t("path") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon, :sel) %>">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td class="actions">
          <%= link_to icon('add') + ' ' + t("select"),
                            select_admin_product_taxon_path(@product, taxon),
                           :remote => true, :class => 'iconlink' %>
        </td>        
      </tr>
    <% end %>
    <% if @taxons.empty? %>
     <tr><td colspan="3"><%= t('no_match_found') %>.</td></tr>
    <% end %>
  </tbody>
</table>

core/app/views/admin/taxons/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("taxon_edit")%></h1>

<%= form_for(:taxon, :url => admin_taxonomy_taxon_url(@taxonomy, @taxon), :html => { :method => :put, :multipart => true}) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <p class="form-buttons">
    <%= button t("update") %> <%= t("or") %> <%= link_to t("cancel"), edit_admin_taxonomy_url(@taxonomy) %>
  </p>
<% end %>

core/app/views/admin/taxons/remove.html.erb
<%= render :partial => "taxon_table", :locals => {:taxons => @taxons} %>

core/app/views/admin/taxons/select.js.erb
$("#selected-taxons").html("<%= escape_javascript(render(:partial => "taxon_table", :locals => {:taxons => @taxons})) %>");
$("#<%= dom_id @taxon, :sel %>").hide();

core/app/views/admin/taxons/selected.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Taxons"} %>
<div id="selected-taxons">
  <%= render :partial => "taxon_table", :locals => {:taxons => @taxons} %>
</div>


<%= form_tag('#') do %>
  <label><%= t('search') %>:</label>
  <input id="searchtext" size="25">
<% end %>

<%= javascript_tag do %>
  function search_for_taxons(){
    jQuery.ajax({
     data: {q: jQuery("#searchtext").val() }, 
     dataType: 'script',
     success: function(request){
       jQuery('#search_hits').html(request);
     },
     type: 'post',
     url: '<%= available_admin_product_taxons_url(@product) %>'
    });
  }

  jQuery("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
      search_for_taxons();

      return false;
    } else {
       return true;
    }
  });

  jQuery("#searchtext").delayedObserver(function() {
    search_for_taxons();
  }, 0.75);
<% end %>
<br/>
<div id="search_hits"></div>